name: Grading workflow

on:
  registry_package:
    types: [published]
  workflow_dispatch:

jobs:

  troubleshoot-activity:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: troubleshooting steps
        run: echo "" #Help the user to troubleshoot the activity
